/* Fichier GÉNÉRÉ par tools/build-lvl0-data.js — ne pas éditer à la main. */
(function () {
  window.DCCLvl0Data = {
  "noms": [
    "Adran",
    "Adran Ofandrus",
    "Adrie Xiloscient",
    "Adrik Beasthunter",
    "Adrik Graybeard",
    "Adventure",
    "Aelfrith",
    "Agis",
    "Ahinar Othronus",
    "Ahvain",
    "Ahvain Hanali",
    "Akthus",
    "Alberich",
    "Alberich Goldenclan",
    "'Aleslosh' Boonblast",
    "'Aleslosh' Scratchpipe",
    "Alethra",
    "Alhamazad",
    "Alovnek",
    "Alton",
    "Alton Deephollow",
    "Alyyn Loudboot",
    "Alyyn 'Weasel' Pilwicken",
    "Amber Everbinder",
    "Ambition",
    "Anakis",
    "Anamwe 'Soilgather' Reese",
    "Anastrianna",
    "Anastrianna Horineth",
    "Ander",
    "Andraste",
    "Andraste Ariessus",
    "Andraste Ofandrus",
    "Andraste Sylvaranth",
    "Andraste Valzumin",
    "Andry Firkin",
    "Andry Harfoot",
    "Anja",
    "Anne Goodearth",
    "Anni Appleblossom",
    "Anni Crumbly",
    "Anton",
    "Arabelyn Deepbeard",
    "Aramil Ariessus",
    "Arannis Tiltathana",
    "Arara",
    "Arara Arnuanna",
    "Arden Chainshield",
    "Argran Fezim",
    "Ari",
    "Arizima",
    "Arn",
    "Artin",
    "Artin Painjaw",
    "Arveene",
    "Arveene Chergoba",
    "Arveene Dyernina",
    "Aseir Greycastle",
    "Aseir Khalid",
    "Aseir Rein",
    "Astar",
    "Aszala",
    "Atala",
    "Atala Basha",
    "Audhild",
    "Audhild Graybeard",
    "Audhild Orcbane",
    "Aust Lathales",
    "Aust Rothenel",
    "Ayasha",
    "Azaki",
    "Azaki Hanali",
    "'Badger' Tinkerflow",
    "Baharoosh Ghesh",
    "Balama Agosto",
    "Balama Pashar",
    "Baok-Re",
    "Baragaz",
    "Barbena Grimhammer",
    "Bardeid Rein",
    "Barendd",
    "Bareris",
    "Bathin",
    "Beiro",
    "Beldelle",
    "Beldelle Strongheart",
    "Beleth",
    "Bernie",
    "Berta Nodov",
    "Betha",
    "Bhenkumbyrznaax Valorean",
    "Bhirar",
    "Bilyur Sympony",
    "Birel Erenaeth",
    "Birel Galanodel",
    "Bjorkus",
    "Blath",
    "Blath Brightwood",
    "Blueberry",
    "Bobbin Goodbarrel",
    "Boggar",
    "Boggar Appleblossom",
    "Bonvir",
    "Bor",
    "Bor Marsk",
    "Borivik",
    "Borivik Iltazyara",
    "Borivik Shemov",
    "Bree Hogcollar",
    "Bree Porridgepot",
    "Brem",
    "Brev Migellic",
    "Bright",
    "Briska",
    "Briska Vay",
    "Brocc Battleflight",
    "Brozhdar",
    "Brug",
    "Brurbarth",
    "Brygus",
    "Bustin Hogcollar",
    "Cade",
    "Cael Sylvaranth",
    "Caemmor",
    "Cahlo",
    "Cam",
    "'Cam' Turen 'Hare' Reese",
    "Camnoc Iranapha",
    "Carlin Brightjewel",
    "Carric",
    "Carric Mystralath",
    "Cefrey",
    "Ceidil",
    "Chao",
    "Chathi",
    "Chathi Ankhalab",
    "Chen",
    "Chenna",
    "Chenna Goldfound",
    "Chenna Tealeaf",
    "Chi",
    "Chien Bai",
    "Chien Qiao",
    "Chui",
    "Chundy Nimblefingers",
    "Circu",
    "Circu Bara",
    "Circu Javya",
    "Circu Trul",
    "Ciresdda Erenaeth",
    "Clethtinthiallor Baradad",
    "Corrin Goldfound",
    "Corrin Tosscobble",
    "Cotter",
    "Crenise",
    "Cressel",
    "Crysania",
    "Cunning",
    "Dae Amakiir",
    "Dagnal",
    "Dahlya Gharti",
    "Dahlya Ralinu",
    "Dalaba",
    "Dannad Widgeon",
    "Danniel",
    "Danniel Brightmoon",
    "Danniel Meadowsweet",
    "Darrak Kinbleeder",
    "Darrak Ungart",
    "Dayereth",
    "Dee",
    "Dee Underbough",
    "Delg",
    "Delg Leffery",
    "Dench Sepret",
    "Despair",
    "Dhazdoro",
    "Dhyrktelonis Faridah",
    "Dhyrktelonis Hirrathak",
    "Diero Domine",
    "Dimleil",
    "Disdain",
    "Dona",
    "Donoa Mucklar",
    "Doom",
    "Dorn",
    "Dorn Evenwood",
    "Dorn Fezim",
    "Doubt",
    "Drashk",
    "Dravin",
    "Dravin Nodov",
    "Dreaii",
    "Dreaii Ariemne",
    "Dud-Kes",
    "Duergath Longblade",
    "Durnik Brightbinder",
    "Duvamil 'Obsidian'",
    "Duvamil 'Otter' Sumika",
    "Duvamil 'Pock'",
    "Dworic Everhold",
    "Ea",
    "Ednia Bloodkith",
    "Egart",
    "Egart Greenleaf",
    "Ehput-Ki",
    "Ehput-Ki Greycastle",
    "Ehput-Ki Windrivver",
    "Einkil Bloodkith",
    "Eiravel Casilltenirra",
    "Eiravel Erenaeth",
    "Ekemon",
    "Enka",
    "Enna Siannodel",
    "Entropy",
    "Eran",
    "Eran Cherrycheeks",
    "Erdan",
    "Erevan Arnuanna",
    "Erinimachis",
    "Errakus",
    "Errich Underfoot",
    "Esmerelda Glenfellow",
    "Esvele Mei",
    "Esvele Windrivver",
    "Euphemia Finefettle",
    "Euphemia High-hill",
    "Evendur Greycastle",
    "Evern",
    "Evern Forenzad",
    "Evern Helsk",
    "Evern Tandris",
    "Exava",
    "Exava Bara",
    "Faelar Aloro",
    "Faen",
    "Fai Huang",
    "Faila",
    "Faila Falone",
    "Fargrim Coincraft",
    "Fargrim Copperdelver",
    "Faurgar",
    "Felosial",
    "Felosial Eathalena",
    "Ferdinand Glenfellow",
    "Ferfanric",
    "Fharngnarthnost Adrex",
    "Fharngnarthnost Rivaan",
    "Fierce",
    "Fildo",
    "Finellen Caebrek",
    "'Fireball' Gimlen",
    "Firsulne",
    "Flint Goblinbane",
    "Franklin Duckweed",
    "Frouse Raulnor",
    "Fyevarra",
    "Fyevarra Murnyethara",
    "Galza 'Onion' Humplebumple",
    "Gammo Cherrycheeks",
    "Gammo Stonebridge",
    "Gar Meliamne",
    "Gardain",
    "Gardain Gemhold",
    "Gardain Trollslayer",
    "Garret Bigheart",
    "Garret Cherrycheeks",
    "Garth",
    "Gelb Brightmoon",
    "Gelt Murnyethara",
    "Geth",
    "Geth Shin",
    "Geth Stormwind",
    "Gidal",
    "Gilbert",
    "Gilbert Brightmoon",
    "Gilbert Goodearth",
    "Gildera Goldfound",
    "Gillydd",
    "Gimgen Kinfoe",
    "Gimgen Rumnaheim",
    "Giogi",
    "Gled",
    "Glenka 'Short' Silverthread",
    "Gnarsh",
    "Goothamic",
    "Gorev",
    "Greed",
    "Grigor",
    "Grim",
    "Grio",
    "Griselda",
    "Grrmmballhyst Antrara",
    "Gunnloda Graybond",
    "Gymthra Gembinder",
    "Gynnie",
    "Gynnie Wildheart",
    "Hadarai",
    "Halafotios",
    "Halimath Holimion",
    "Halimath Sylvenel",
    "Harbek Shadowfist",
    "Harol",
    "Harol Honeypot",
    "Harriet",
    "Harrow",
    "Haseid",
    "Hatae",
    "'Heartbreak' Maekkelferce",
    "Helgret Holderhek",
    "Helja Lowbrow",
    "Hennet",
    "Hlin",
    "Hob Grogbelly",
    "Holg",
    "HRillka",
    "Hshhsstoroth Donaar",
    "Hulmar",
    "Hulmarra",
    "Hulmarra Chernin",
    "Hulmarra Dyernina",
    "Ibo",
    "Ielenia Iranapha",
    "Igan",
    "Ignominy",
    "Igor Meadowdown",
    "Immith",
    "Immith Stormwind",
    "Imzel",
    "Imzel Dotsk",
    "Inassa 'Blinky' Daergel",
    "Inassa 'Breack' Webspin",
    "Innovation",
    "Ir",
    "Irann",
    "Irann Amastacia",
    "Irann Firahel",
    "Ire",
    "Irnaya",
    "Ishte",
    "Ivan",
    "Ivellios Dalanthan",
    "Ivor",
    "Ivor Bersk",
    "Ivor Dotsk",
    "'Jaguar' Maekkelferce",
    "Jallarzi",
    "Jamira",
    "Jandar",
    "Jandar Chergoba",
    "Jandar Marsk",
    "Janik Grezar",
    "Janik Sarv",
    "Jarana",
    "Jarsali Horineth",
    "Jarsali Suithrasas",
    "Jasmal",
    "Jasmal Rein",
    "Jelenneth Horineth",
    "Jeltina 'Nickledime' Fizzletop",
    "Jerynomonis Rivaan",
    "Jhessail",
    "Jia",
    "Jia Mostana",
    "Jiang",
    "Jo",
    "Jo Crabapple",
    "Jo Fairtrot",
    "Jodira Gobblefirn",
    "Journey",
    "Jozica Tandris",
    "Jun Domine",
    "Jun Stayanoga",
    "Junillell",
    "Juri",
    "Kairut",
    "Kanithar",
    "Kanithar Stayanoga",
    "Kansif Astorio",
    "Kao Wen",
    "Kara Dotsk",
    "Karash",
    "Kasdeya",
    "Katernin",
    "Kazak Trollbleeder",
    "Keith Goodearth",
    "Keith Greenleaf",
    "Kerania",
    "Keranios",
    "Kerri",
    "Keth",
    "Kethoth",
    "Kethoth Jassan",
    "Kethra",
    "Kethra Hornraven",
    "Kevin Tallfellow",
    "Khemed",
    "Khemed Dumein",
    "Khemed Fezim",
    "Kildrak Coinsmite",
    "Kimbatuul Dentratha",
    "Kimbatuul Quespa",
    "Kipper",
    "Klattic",
    "Korag",
    "Korbus 'Dragon'",
    "Korfel Ariemne",
    "Kosef Astorio",
    "Krolmun",
    "Kromryl Morigak",
    "Kung Mei",
    "Kung Shui",
    "Kuonu",
    "Kuzro",
    "Kyris",
    "Lander Brightwood",
    "Lao Long",
    "Lazam",
    "Lei Shin",
    "Lelleilsul",
    "Len",
    "Lestra",
    "Lezre",
    "Lidda",
    "Liftrasa",
    "Liftrasa Gemhelm",
    "Liftrasa Grudgesmith",
    "Lilmutch Honeypot",
    "Lilriadoc Honeypot",
    "Lindal Tallfellow",
    "Ling Qiao",
    "Ling Shan",
    "Long",
    "Loobnes Coinspin 'Cam' Nibblefebble",
    "Love",
    "Lucan",
    "Luck",
    "Luisa Pisacar",
    "Lumia Macav",
    "Lureene Buckman",
    "Lureene Mostana",
    "Luth Brightwood",
    "Luth Hornraven",
    "Luth Stormwind",
    "Luthra 'Wrinkles'",
    "Lyzolda",
    "'Mad' Pilwicken",
    "Madislak",
    "Mai Hanadrin",
    "Malark Dundragon",
    "Malark Evenwood",
    "Malark Tallstag",
    "Malmus",
    "Malquis Xiloscient",
    "Manwick Quivergrass",
    "Mara",
    "Mara Astorio",
    "Mara Holimion",
    "Mara Marsk",
    "Mara Windrivver",
    "Marastyr",
    "Marcon",
    "Marta Falone",
    "Marta Pisacar",
    "Mastema",
    "Mavxikas",
    "Mehmen",
    "Mehmen Khalid",
    "Mei",
    "Mei Fai",
    "Mei Jun",
    "Mei On",
    "Meilil Basha",
    "Meilil Buckman",
    "Meilil Jassan",
    "Melech",
    "Melislek",
    "Menetavro",
    "Meng",
    "Merric",
    "Merric Whispermouse",
    "Mesalandril Ariessus",
    "Mialee",
    "Mialee Fasharash",
    "Micas",
    "Micas Tandris",
    "Milo Copperkettle",
    "Milo Dimmock",
    "Miotri Sarv",
    "Miri Buckman",
    "Miri Dundragon",
    "Mival",
    "Modean",
    "Mohradyllion Zykroff",
    "Morai",
    "Mordal",
    "Morg Lao",
    "Morgran Rakankrak",
    "Mormo",
    "Morrin Smoothhands",
    "Morthos",
    "Mubran",
    "Mui",
    "Muirdal Coinfist",
    "Mumed",
    "Mumed Fezim",
    "Murgen",
    "Murithi",
    "Murithi Ankhalab",
    "Murnir Strakeln",
    "Myria Silvereyes",
    "Mysmura Goldshaper",
    "Naal",
    "Naal Lathales",
    "Naal Withrethin",
    "Nalaed",
    "Nalral",
    "Nalvara Elasatra",
    "Nambra Hanali",
    "Namfoodle 'Twitch' Ironhide",
    "Nars Sarv",
    "Natali",
    "Natali Bersk",
    "Nathuki",
    "Navarra Mei",
    "Nebun",
    "Nedress",
    "Neeshka",
    "Nefara",
    "Nefara Grezar",
    "Neheb",
    "Nemeia",
    "Nemmonis Gargax",
    "Nesterin Hanali",
    "Nesterin Lathales",
    "Nesterin Sylvenel",
    "'Nickledime' Wildwander",
    "Nikki Lackstern",
    "Nikul 'Zee' Mucklar",
    "Nil Pin",
    "Nirikov",
    "Nitt",
    "Nora Goldfound",
    "Noraka",
    "'Noselick' Garrick",
    "Nulara",
    "Nulara Ankhalab",
    "Nulara Anskuld",
    "Nundrini",
    "Nutae Valzumin",
    "Obez",
    "Oda 'Saddle'",
    "Odet Stoutman",
    "Odorr Kulenov",
    "Olivia Smoothhands",
    "Olma",
    "Olma Starag",
    "On",
    "Onnurth",
    "Ophinshtalajiir Zykroff",
    "Oppah 'Cam' Nucklestamp",
    "Oppah 'Fawn' Boondiggles",
    "Oppleby",
    "Oppleby Cobblelob Albaratie",
    "Orexijandilin Rhogar",
    "Orianna",
    "Oriff",
    "Oriff Bofdann",
    "Orupos 'Elf' Geparas",
    "Orupos 'Slayer'",
    "Ottagunda Furrows",
    "Ottagunda Greenleaf",
    "Ouriki",
    "Ovina Brightbringer",
    "Ovina Ruby-Eye",
    "Palla",
    "Panic",
    "Pavel Pin",
    "Pearl",
    "Pearl Brushgather",
    "'Pearl' Glitterfingers",
    "Pearl Wiseacre",
    "Pennie Leagallow",
    "Pfaphnyrennish Megren",
    "Philomena Strongbones",
    "Phrahdrandon Kiirith",
    "Pieron",
    "Pieron Bersk",
    "'Pig' Goldhelm",
    "Pipne 'Poppy'",
    "'Pock' Brightjewel",
    "Pog 'Nickledime' Waggletop",
    "Portia Bigheart",
    "Portia Strongbones",
    "Prezhlek",
    "Py",
    "Qemuel",
    "Quara Falone",
    "Quara Pisacar",
    "Quilla 'Ivory' Ubblur",
    "Quillathe",
    "Qyxpahrgh Hethress",
    "'Rabbit' Silverthread",
    "Radolak",
    "Ralmevik",
    "Ralmevik Iltazyara",
    "Ramas",
    "Ramas Uuthrakt",
    "Ranala 'Forest' Leadstopper",
    "Randal",
    "Randulf Tenpenny",
    "Rari",
    "'Redcap' Sumika",
    "Redemption",
    "Redgar",
    "Redhat",
    "Regnum Horrog",
    "Ren Liadon",
    "Rengu",
    "Rhordon",
    "Ridthi",
    "Ridthi Yaeldrin",
    "Rienlarna Ariessus",
    "Rienlarna Cithreth",
    "Rienlarna Othronus",
    "Rieta",
    "Rogad Yaszen",
    "Romero",
    "Romero Marivaldi",
    "Rosa High-hill",
    "Rose Goodbarrel",
    "Rose Hogcollar",
    "Rowan Bersk",
    "Rowan Dundragon",
    "Rowan Greycastle",
    "Rowan Sum",
    "Rowan Tallstag",
    "Rrath",
    "Rrath Fezim",
    "Ruba",
    "Ruba Grezar",
    "Runlen",
    "Sael",
    "Sai",
    "Salazar",
    "Salazar Agosto",
    "Salazar Domine",
    "Sam",
    "Sandruu",
    "Sandula Hillstrike",
    "Sannl Gemsmite",
    "Sannl Goldfinder",
    "Sariel Iranapha",
    "Sarwyn",
    "Sasolis",
    "Scrag",
    "Scrag Pisacar",
    "Sefris Hahpet",
    "Seipora",
    "Sekra",
    "Sergiu",
    "Sergiu Macav",
    "Sergor",
    "Sfena",
    "Shanairla",
    "Shandri Sepret",
    "Shardon Elderberry",
    "Shaumar Ramondo",
    "Shava",
    "Shax",
    "Sheggen",
    "Shevarra Murnyethara",
    "Shin Qiao",
    "Shui",
    "Shui Evenwood",
    "Shump Chergoba",
    "Silifrey",
    "Silifrey Hornraven",
    "Skaarzborroosh Jezean",
    "Skorlok Firewarden",
    "'Slapdash' Gobblefirn",
    "Sokali",
    "So-Kehur",
    "So-Kehur Fezim",
    "Stacee Sunmeadow",
    "Stedd Amblecrown",
    "Stedd Tallstag",
    "Strava",
    "Strava Gharti",
    "'Stumbleduck' Ningel",
    "Sturm",
    "Sudeiman",
    "Sum Bai",
    "Sum Jiang",
    "Sum Jun",
    "Sum Long",
    "Sum Tai",
    "Sumnarghthrysh Gesrethe",
    "Sumnes Lathalath",
    "Tahngarth",
    "Tai",
    "Taklinn",
    "Taklinn Orcbane",
    "Taklinn Skybinder",
    "Tammith Murnyethara",
    "Tana",
    "Tana Chernin",
    "Tanta Swiftwhistle",
    "Tarilniell Arnuanna",
    "Tasha",
    "Tawar",
    "Tazon-Dud",
    "Tazryl",
    "Tenena 'Unship' Grapeleaf",
    "Tenser",
    "Tervaround 'Salamander' Boondiggles",
    "Tessele Tallstag",
    "Teysa",
    "Thamior Teinithra",
    "Thea Deephollow",
    "Theirastra",
    "Thendri",
    "Theogrim",
    "Therana Ofandrus",
    "Theren Daloroth",
    "Theriatis",
    "Theriatis Nailo",
    "Thervan",
    "Thervan Aloro",
    "Thiu",
    "Thodris Bofdann",
    "Thola",
    "Thola Anskuld",
    "Thoradin Loderr",
    "Thoradin Trueanvil",
    "Thuridan Aloro",
    "Thyrogog",
    "Tiammanthyllish Dentratha",
    "Tibbnep 'Cards' Tolstone",
    "Tibor Grezar",
    "Tibor Macav",
    "Tibor Ralinu",
    "Tibor Rokiric",
    "Tiepraa Garrick",
    "Tinir",
    "Tippletoe 'Cards' Uskar",
    "Tithian",
    "Tlaathque Netyoive",
    "Tocka 'Lucky' Ubblur",
    "Tordek",
    "Tordrid",
    "Trag",
    "Traubon Hammerlord",
    "Traubon Holderhek",
    "Traulam",
    "Travok Skyfinder",
    "Tribi Ubblur",
    "Trifyx 'Elf' Maekkelferce",
    "Trouble",
    "Tsia",
    "Turnuroth Ghesh",
    "Tye",
    "Tyna Deephollow",
    "Tyna Whispermouse",
    "Uhlar",
    "Ulfgar Foamcraft",
    "Ulfrak Shadowfall",
    "Umara",
    "Umara Fezim",
    "Umbero Marivaldi",
    "Umbero Ramondo",
    "Uovana",
    "Upizeil",
    "Uraim",
    "Urhur",
    "Urhur Nathandem",
    "Urhur Sepret",
    "Urth",
    "Uthemar",
    "Uzza",
    "Vadania",
    "Valanthe",
    "Valen",
    "Valen Macav",
    "Valen Trul",
    "Vallis 'Merry' Shadowmountain",
    "Vanchu",
    "Vangdondalor Pandjed",
    "Varazina Broodaxe",
    "Varis",
    "Varis Ariessus",
    "Varis Wasanthi",
    "Varis Yaeldrin",
    "Veit Kinsmiter",
    "Verin",
    "Verna Whispermouse",
    "Verthisathurgiesh Hirrathak",
    "Veska",
    "Vina",
    "Vina Nodov",
    "Virtue",
    "Vladislak",
    "Vladislak Agosto",
    "Vladislak Iltazyara",
    "Voka",
    "Voka Trul",
    "Vonana Caebrek",
    "Vonana Ruby-Eye",
    "Vorel",
    "Vorel Migellic",
    "Vraslak",
    "Wan Qiao",
    "Waywocket Cobblelob",
    "Wen",
    "Wendel Sunmeadow",
    "Westra Helder",
    "Whurbin Earthguard",
    "Whurbin Silveraxe",
    "Whurdred Trollfeller",
    "Wildon 'Mouse' Murnig",
    "Willow",
    "Willow Greenbottle",
    "Wioh",
    "'Wishful' Fiddlefen",
    "Woe",
    "Wrevyn Horcusporcus",
    "Wystongjiir Direcris",
    "Wystongjiir Trynnicus",
    "Wystongjiir Vrondiss",
    "Xanaphia",
    "Xappan",
    "Yarjerit Maagog",
    "Yelka",
    "Ypoudoris",
    "Yuldra",
    "Yuldra Hornraven",
    "Yuldra Stayanoga",
    "Yuldra Ulmokina",
    "Yumanea Daenala",
    "Yumanea Othronus",
    "Yurgunn",
    "Zak-Mak",
    "Zamagun Oldblood",
    "Zepar",
    "Zija",
    "Zija Grezar",
    "Zija Kos",
    "Zija Yaszen",
    "Zimza",
    "Zirehluh",
    "Znanlen Tolstone",
    "Zoka",
    "Zolis",
    "Zolis Fezim",
    "Zolis Marivaldi",
    "Zolis Ulmokina",
    "Zora Bersk",
    "Zora Starag",
    "Zorbu",
    "Zunak",
    "Zunak Pijha",
    "Zuruh"
  ],
  "metiers": [
    {
      "metier": "Alchimiste",
      "arme": "Bâton 1d4",
      "equipement": "Huile, 1 flasque"
    },
    {
      "metier": "Apiculteur",
      "arme": "Bâton 1d4",
      "equipement": "Pot de miel"
    },
    {
      "metier": "Apprenti mage",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Grimoire noir"
    },
    {
      "metier": "Armurier",
      "arme": "Marteau (comme Gourdin 1d4)",
      "equipement": "Heaume en fer"
    },
    {
      "metier": "Astrologue",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Longue-vue"
    },
    {
      "metier": "Barbier",
      "arme": "Rasoir (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Ciseaux"
    },
    {
      "metier": "Bedeau",
      "arme": "Bâton 1d4",
      "equipement": "Symbole sacré"
    },
    {
      "metier": "Berger",
      "arme": "Bâton 1d4",
      "equipement": "Chien de berger"
    },
    {
      "metier": "Boucher",
      "arme": "Hachoir (comme Hachette 1d6 3/6/9)",
      "equipement": "Tranche de viande"
    },
    {
      "metier": "Bouffon",
      "arme": "Fléchette 1d4 6/12/18",
      "equipement": "Vêtements de soie"
    },
    {
      "metier": "Bûcheron",
      "arme": "Hachette 1d6 3/6/9",
      "equipement": "Fagot de bois"
    },
    {
      "metier": "Bûcheron",
      "arme": "Hachette 1d6 3/6/9",
      "equipement": "Fagot de bois"
    },
    {
      "metier": "Bûcheron",
      "arme": "Hachette 1d6 3/6/9",
      "equipement": "Fagot de bois"
    },
    {
      "metier": "Chaman",
      "arme": "Masse 1d6",
      "equipement": "Herbes, 500 g"
    },
    {
      "metier": "Charron",
      "arme": "Gourdin 1d4",
      "equipement": "Charrette à bras"
    },
    {
      "metier": "Chasseur",
      "arme": "Arc court 1d6 15/30/45",
      "equipement": "Peau de cerf"
    },
    {
      "metier": "Chasseur",
      "arme": "Arc court 1d6 15/30/45",
      "equipement": "Peau de cerf"
    },
    {
      "metier": "Collecteur d’impôts",
      "arme": "Épée longue 1d8",
      "equipement": "100 pc"
    },
    {
      "metier": "Contrebandier",
      "arme": "Fronde 1d4 12/25/50",
      "equipement": "Sac étanche"
    },
    {
      "metier": "Cordier",
      "arme": "Couteau (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Corde, 30 m"
    },
    {
      "metier": "Cordonnier",
      "arme": "Poinçon (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Chausse-pied"
    },
    {
      "metier": "Coupeur de bourse",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Petit coffre"
    },
    {
      "metier": "Diseur de bonne aventure",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Jeu de tarot"
    },
    {
      "metier": "Docker",
      "arme": "Perche (comme Bâton 1d4)",
      "equipement": "1 livre de JdR en retard"
    },
    {
      "metier": "Dresseur",
      "arme": "Gourdin 1d4",
      "equipement": "Poney"
    },
    {
      "metier": "Écuyer",
      "arme": "Épée longue 1d8",
      "equipement": "Heaume en acier"
    },
    {
      "metier": "Écuyer",
      "arme": "Épée longue 1d8",
      "equipement": "Heaume en acier"
    },
    {
      "metier": "Elfe artisan",
      "arme": "Bâton 1d4",
      "equipement": "Argile, 500 g"
    },
    {
      "metier": "Elfe avocat",
      "arme": "Plume (comme Fléchette 1d4 6/12/18)",
      "equipement": "Livre"
    },
    {
      "metier": "Elfe cirier",
      "arme": "Ciseaux (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Chandelles, 20"
    },
    {
      "metier": "Elfe fauconnier",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Faucon"
    },
    {
      "metier": "Elfe forestier",
      "arme": "Bâton 1d4",
      "equipement": "Herbes, 500 g"
    },
    {
      "metier": "Elfe forestier",
      "arme": "Bâton 1d4",
      "equipement": "Herbes, 500 g"
    },
    {
      "metier": "Elfe navigateur",
      "arme": "Arc court 1d6 15/30/45",
      "equipement": "Longue-vue"
    },
    {
      "metier": "Elfe sage",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Parchemin et plume"
    },
    {
      "metier": "Elfe sage",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Parchemin et plume"
    },
    {
      "metier": "Elfe souffleur de verre",
      "arme": "Marteau (comme Gourdin 1d4)",
      "equipement": "Perles de verre"
    },
    {
      "metier": "Esclave",
      "arme": "Gourdin 1d4",
      "equipement": "Caillou de forme bizarre"
    },
    {
      "metier": "Escroc",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Cape de qualité"
    },
    {
      "metier": "Excavateur",
      "arme": "Pelle (comme Bâton 1d4)",
      "equipement": "Poussière fine, 500 g"
    },
    {
      "metier": "Fermier (patate)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (blé)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (navet)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (maïs)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (riz)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (panais)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (radis)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (rutabaga)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Fermier (choux)",
      "arme": "Fourche (comme Lance 1d8)",
      "equipement": "Poule"
    },
    {
      "metier": "Forgeron",
      "arme": "Marteau (comme Gourdin 1d4)",
      "equipement": "Pinces en acier"
    },
    {
      "metier": "Fossoyeur",
      "arme": "Pelle (comme Bâton 1d4)",
      "equipement": "Truelle"
    },
    {
      "metier": "Fossoyeur",
      "arme": "Pelle (comme Bâton 1d4)",
      "equipement": "Truelle"
    },
    {
      "metier": "Fromager",
      "arme": "Matraque (comme Bâton 1d4)",
      "equipement": "Fromage puant"
    },
    {
      "metier": "Gamin des rues",
      "arme": "Bout de bois (comme Gourdin 1d4)",
      "equipement": "Sébile"
    },
    {
      "metier": "Garde de caravane",
      "arme": "Épée courte 1d6",
      "equipement": "Drap, 1 m"
    },
    {
      "metier": "Guérisseur",
      "arme": "Gourdin 1d4",
      "equipement": "Eau bénite, 1 fiole"
    },
    {
      "metier": "Halfelin bohémien",
      "arme": "Fronde 1d4 12/25/50",
      "equipement": "Poupée vaudou"
    },
    {
      "metier": "Halfelin gantier",
      "arme": "Poinçon (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Gants, 4 paires"
    },
    {
      "metier": "Halfelin marin",
      "arme": "Couteau (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Voile, 2 m"
    },
    {
      "metier": "Halfelin mercier",
      "arme": "Ciseaux (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Costumes, 3 ensembles"
    },
    {
      "metier": "Halfelin négociant",
      "arme": "Épée courte 1d6",
      "equipement": "20 pa"
    },
    {
      "metier": "Halfelin teinturier",
      "arme": "Bâton 1d4",
      "equipement": "Tissu, 3 m"
    },
    {
      "metier": "Halfelin teinturier",
      "arme": "Bâton 1d4",
      "equipement": "Tissu, 3 m"
    },
    {
      "metier": "Halfelin usurier",
      "arme": "Épée courte 1d6",
      "equipement": "5 po, 10 pa, 200 pc"
    },
    {
      "metier": "Halfelin vagabond",
      "arme": "Gourdin 1d4",
      "equipement": "Coupelle de mendiant"
    },
    {
      "metier": "Halfelin volailler",
      "arme": "Hachette 1d6 3/6/9",
      "equipement": "Viande de poulet, 2 kg"
    },
    {
      "metier": "Herboriste",
      "arme": "Gourdin 1d4",
      "equipement": "Herbes, 500 g"
    },
    {
      "metier": "Hors-la-loi",
      "arme": "Épée courte 1d6",
      "equipement": "Armure de cuir"
    },
    {
      "metier": "Joaillier",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Gemmes valant 20 po"
    },
    {
      "metier": "Joueur",
      "arme": "Gourdin 1d4",
      "equipement": "Dés"
    },
    {
      "metier": "Maraîcher",
      "arme": "Couteau (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Fruit"
    },
    {
      "metier": "Marchand",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "4 po, 14 pa, 27 pc"
    },
    {
      "metier": "Mendiant",
      "arme": "Gourdin 1d4",
      "equipement": "Fromage"
    },
    {
      "metier": "Mendiant de guilde",
      "arme": "Fronde 1d4 12/25/50",
      "equipement": "Béquilles"
    },
    {
      "metier": "Mendiant de guilde",
      "arme": "Fronde 1d4 12/25/50",
      "equipement": "Béquilles"
    },
    {
      "metier": "Ménestrel",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Ukulélé"
    },
    {
      "metier": "Mercenaire",
      "arme": "Épée longue 1d8",
      "equipement": "Armure de peau"
    },
    {
      "metier": "Meunier/Boulanger",
      "arme": "Gourdin 1d4",
      "equipement": "Farine, 500 g"
    },
    {
      "metier": "Nain apothicaire",
      "arme": "Matraque (comme Bâton 1d4)",
      "equipement": "Flacon en acier"
    },
    {
      "metier": "Nain coffretier",
      "arme": "Burin (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Bois, 5 kg"
    },
    {
      "metier": "Nain éleveur",
      "arme": "Bâton 1d4",
      "equipement": "Truie"
    },
    {
      "metier": "Nain forgeron",
      "arme": "Marteau (comme Gourdin 1d4)",
      "equipement": "Mithril, 30 g"
    },
    {
      "metier": "Nain maçon",
      "arme": "Marteau (comme Gourdin 1d4)",
      "equipement": "Pierre, 5 kg"
    },
    {
      "metier": "Nain maçon",
      "arme": "Marteau (comme Gourdin 1d4)",
      "equipement": "Pierre, 5 kg"
    },
    {
      "metier": "Nain mineur",
      "arme": "Pioche (comme Gourdin 1d4)",
      "equipement": "Lanterne"
    },
    {
      "metier": "Nain mineur",
      "arme": "Pioche (comme Gourdin 1d4)",
      "equipement": "Lanterne"
    },
    {
      "metier": "Nain myciculteur",
      "arme": "Pelle (comme Bâton 1d4)",
      "equipement": "Sacoche"
    },
    {
      "metier": "Nain ratier",
      "arme": "Gourdin 1d4",
      "equipement": "Filet"
    },
    {
      "metier": "Noble",
      "arme": "Épée longue 1d8",
      "equipement": "Anneau d’or (10 po)"
    },
    {
      "metier": "Orphelin",
      "arme": "Gourdin 1d4",
      "equipement": "Poupée de chiffon"
    },
    {
      "metier": "Palefrenier",
      "arme": "Bâton 1d4",
      "equipement": "Bride"
    },
    {
      "metier": "Scribe",
      "arme": "Fléchette 1d4 6/12/18",
      "equipement": "Parchemin, 10 feuilles"
    },
    {
      "metier": "Serrurier",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Outils de précision"
    },
    {
      "metier": "Serviteur",
      "arme": "Bâton 1d4",
      "equipement": "Médaillon"
    },
    {
      "metier": "Soldat",
      "arme": "Lance 1d8",
      "equipement": "Bouclier"
    },
    {
      "metier": "Tisserand",
      "arme": "Dague 1d4/1d10 3/6/9",
      "equipement": "Vêtements de qualité"
    },
    {
      "metier": "Tonnelier",
      "arme": "Pied-de-biche (comme Gourdin 1d4)",
      "equipement": "Tonneau"
    },
    {
      "metier": "Trappeur",
      "arme": "Fronde 1d4 12/25/50",
      "equipement": "Fourrure de blaireau"
    },
    {
      "metier": "Trappeur",
      "arme": "Fronde 1d4 12/25/50",
      "equipement": "Fourrure de blaireau"
    },
    {
      "metier": "Vidangeur de latrines",
      "arme": "Truelle (comme Dague 1d4/1d10 3/6/9)",
      "equipement": "Sac d’excréments"
    }
  ],
  "chance": [
    "Hiver rigoureux : Tous les jets d’attaque",
    "Le taureau : Jets d’attaque au corps à corps",
    "Jour de chance : Jets d’attaque à distance",
    "Élevé par les loups : Jets d’attaque à mains nues",
    "Conçu à cheval : Jets d’attaque montée",
    "Né sur le champ de bataille : Jets de dégâts",
    "Voie de l’ours : Jets de dégâts au corps à corps",
    "Œil de faucon : Jets de dégâts à distance",
    "Chasseur en meute : Jets d’attaque et dégâts avec l’arme de départ de niveau",
    "Né dans l’atelier : Tests de compétence (y compris les compétences de voleur)",
    "Ruse du renard : Détecter/désamorcer les pièges",
    "Trèfle à quatre feuilles : Trouver les passages secrets",
    "Septième fils : Tests d’incantation",
    "La tempête déchaînée : Dégâts des sorts",
    "Cœur vertueux : Tests pour Repousser les impies",
    "Survivant de la peste : Soins magiques",
    "Bon présage : Jets de sauvegarde",
    "Ange gardien : Jets de sauvegarde pour échapper aux pièges",
    "Mordu par une araignée : Jets de sauvegarde contre le poison",
    "Frappé par la foudre : Jets de sauvegarde de Réflexes",
    "Survivant d’une famine : Jets de sauvegarde de Vigueur",
    "A résisté à la tentation : Jets de sauvegarde de Volonté",
    "Maison protégée : Classe d’Armure",
    "Vitesse du cobra : Initiative",
    "Récolte abondante : Points de vie (s’applique à chaque niveau)",
    "Bras du guerrier : Tables de coups critiques (double le modificateur de chance)",
    "Demeure maudite : Jets de corruption",
    "L’étoile brisée : Maladresses (double le modificateur de chance)",
    "Chant d’oiseau : Nombre de langues",
    "Enfant sauvage : Vitesse (chaque +1/-1 = mouvement +1,5 m/-1,5 m)"
  ],
  "equipement": [
    "Bougie",
    "Chaîne, 3 m",
    "Coffre, vide",
    "Corde, 15 m",
    "Craie, 1 morceau",
    "Eau bénite 1d4 MV/DN/D",
    "Flasque, vide",
    "Gourde",
    "Grappin",
    "Huile 1d6 + DD10 Ref/tour",
    "Lanterne",
    "Marteau, petit",
    "Miroir de poche",
    "Outils de voleur",
    "Perche, 3 m",
    "Pied-de-biche",
    "Pointe en fer, unité",
    "Rations, par jour",
    "Sac, grand",
    "Sac, petit",
    "Sac à dos",
    "Silex & amadou",
    "Symbole sacré",
    "Torche, unité"
  ]
};
})();
